### ISSUE TITLE
Can you provide the config file for rotated dab-detr?

### ISSUE THREAD

**Issue by kouyuanbo** [SIAnalytics/RHINO#1]
Thanks for the great work!Recently,I attempt to code the rotated dab-detr, but the training result is so bad, such as the first epoch on dotav1, the ap is 0.  In this repository,there is the code for rotated dab-detr, but the result of dab-detr is not in the paper.And there is no config for dab-detr.I want to check what's wrong with my code recording to this repo.Could you provide the config file for rotated dab-detr?

**Comment by kouyuanbo** [comment]
I use the code in this repo and try to train dab-detr with the config file writen by myself.But I got the similar result.Like after the first epoch,the ap is 0.

**Comment by kouyuanbo** [comment]
![image](https://github.com/SIAnalytics/RHINO/assets/58502493/33649b96-2b74-4f8d-a25a-7ce937bc351c)

**Comment by nijkah** [comment]
@kouyuanbo Thank you for your interest in our work.
After reproducing the Rotated Deformable-DETR baseline, we attempted to reproduce the rotated versions of DAB-DETR and DINO in parallel. While we succeeded in implementing the rotated version of DINO, we were unsuccessful with DAB-DETR.
The main reason is that DAB-DETR contains miscellaneous technical details such as modulated width & height cross-attention, making it difficult to fully integrate the rotated anchors. Therefore, we decided to focus on the rotated DINO.

**Comment by kouyuanbo** [comment]
> @kouyuanbo Thank you for your interest in our work. After reproducing the Rotated Deformable-DETR baseline, we attempted to reproduce the rotated versions of DAB-DETR and DINO in parallel. While we succeeded in implementing the rotated version of DINO, we were unsuccessful with DAB-DETR. The main reason is that DAB-DETR contains miscellaneous technical details such as modulated width & height cross-attention, making it difficult to fully integrate the rotated anchors. Therefore, we decided to focus on the rotated DINO.

@nijkah Thanks a lot for your reply!Your reply answer the question which has been confusing me for a long time.
